# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release-job:
    runs-on: ubuntu-latest
    name: Releasing
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Run a one-line script
        run: echo release!

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo normal!
